# Cloud Build configuration for qiq-mcp-server
# Builds and pushes a Docker image to Artifact Registry.
# Make sure the Artifact Registry repository exists first:
#   gcloud artifacts repositories create ${_REPOSITORY} \
#     --repository-format=docker --location=${_REGION}
# And grant Cloud Build SA writer access if needed.

substitutions:
  _REGION: europe-west1     # Change if you use a different region
  _REPOSITORY: mcp-server   # Artifact Registry repo name (must exist)
  _IMAGE: mcp-server        # Image name inside the repo
  _SERVICE: qiq-mcp-server  # Cloud Run service name

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Ensure Artifact Registry repo exists'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        echo "Ensuring Artifact Registry repo '${_REPOSITORY}' exists in region '${_REGION}' for project '$PROJECT_ID'"
        # List repos; if not found, create it. This is safe to run repeatedly.
        if ! gcloud artifacts repositories describe "${_REPOSITORY}" --location="${_REGION}" >/dev/null 2>&1; then
          echo "Repository not found. Creating..."
          gcloud artifacts repositories create "${_REPOSITORY}" \
            --repository-format=docker \
            --location="${_REGION}" \
            --description="Docker repo for qiq-mcp-server"
          echo "Repository created."
        else
          echo "Repository already exists."
        fi

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push commit tag'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push latest tag'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        IMAGE_URI="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest"
        echo "Deploying $IMAGE_URI to Cloud Run service ${_SERVICE} in region ${_REGION}"
        gcloud run deploy "${_SERVICE}" \
          --image "${IMAGE_URI}" \
          --region "${_REGION}" \
          --allow-unauthenticated \
          --port 8080

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest'
